apiVersion:v1
kind:Service
metadata:
  name: nodejs-kubernetes
  labels:
    app: nodejs-kubernetes
spec:
  selector:
    app: nodejs-kubernetes
  ports:
  - port : 3000
    protocol: TCP
    nodePort :30001
  type: LoadBalancer